services:
  - type: web
    name: mobjanebi
    runtime: dotnet
    buildCommand: "cd EShop && dotnet publish -c Release -o ../publish"
    publishDir: "publish"
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
